apiVersion: apps/v1
kind: Deployment
metadata:
  name: myproject-deployment
  labels:
    app: myproject
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myproject
  template:
    metadata:
      labels:
        app: myproject
    spec:
      containers:
      - name: myproject
        image: rishabhnama/myproject:latest
        ports:
        - containerPort: 80
        
---
apiVersion: v1
kind: Service
metadata:
  name: myproject-service
spec:
  type: NodePort
  selector:
    app: myproject
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000


